from setuptools import setup

setup(
    name='ScammerFlooder',
    version='0.2',
    packages=['venv.lib.python3.6.site-packages.jwt', 'venv.lib.python3.6.site-packages.jwt.contrib',
              'venv.lib.python3.6.site-packages.jwt.contrib.algorithms', 'venv.lib.python3.6.site-packages.pip',
              'venv.lib.python3.6.site-packages.pip.req', 'venv.lib.python3.6.site-packages.pip.vcs',
              'venv.lib.python3.6.site-packages.pip.utils', 'venv.lib.python3.6.site-packages.pip.compat',
              'venv.lib.python3.6.site-packages.pip.models', 'venv.lib.python3.6.site-packages.pip._vendor',
              'venv.lib.python3.6.site-packages.pip._vendor.idna',
              'venv.lib.python3.6.site-packages.pip._vendor.certifi',
              'venv.lib.python3.6.site-packages.pip._vendor.chardet',
              'venv.lib.python3.6.site-packages.pip._vendor.chardet.cli',
              'venv.lib.python3.6.site-packages.pip._vendor.distlib',
              'venv.lib.python3.6.site-packages.pip._vendor.distlib._backport',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.util',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.contrib',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.contrib._securetransport',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages.backports',
              'venv.lib.python3.6.site-packages.pip._vendor.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.pip._vendor.colorama',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib._trie',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.filters',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treewalkers',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treeadapters',
              'venv.lib.python3.6.site-packages.pip._vendor.html5lib.treebuilders',
              'venv.lib.python3.6.site-packages.pip._vendor.lockfile',
              'venv.lib.python3.6.site-packages.pip._vendor.progress',
              'venv.lib.python3.6.site-packages.pip._vendor.requests',
              'venv.lib.python3.6.site-packages.pip._vendor.packaging',
              'venv.lib.python3.6.site-packages.pip._vendor.cachecontrol',
              'venv.lib.python3.6.site-packages.pip._vendor.cachecontrol.caches',
              'venv.lib.python3.6.site-packages.pip._vendor.webencodings',
              'venv.lib.python3.6.site-packages.pip._vendor.pkg_resources',
              'venv.lib.python3.6.site-packages.pip.commands', 'venv.lib.python3.6.site-packages.pip.operations',
              'venv.lib.python3.6.site-packages.idna', 'venv.lib.python3.6.site-packages.pytz',
              'venv.lib.python3.6.site-packages.twilio', 'venv.lib.python3.6.site-packages.twilio.jwt',
              'venv.lib.python3.6.site-packages.twilio.jwt.client',
              'venv.lib.python3.6.site-packages.twilio.jwt.taskrouter',
              'venv.lib.python3.6.site-packages.twilio.jwt.validation',
              'venv.lib.python3.6.site-packages.twilio.jwt.access_token',
              'venv.lib.python3.6.site-packages.twilio.base', 'venv.lib.python3.6.site-packages.twilio.http',
              'venv.lib.python3.6.site-packages.twilio.rest', 'venv.lib.python3.6.site-packages.twilio.rest.api',
              'venv.lib.python3.6.site-packages.twilio.rest.api.v2010',
              'venv.lib.python3.6.site-packages.twilio.rest.api.v2010.account',
              'venv.lib.python3.6.site-packages.twilio.rest.api.v2010.account.sip',
              'venv.lib.python3.6.site-packages.twilio.rest.api.v2010.account.sip.domain',
              'venv.lib.python3.6.site-packages.twilio.rest.api.v2010.account.sip.credential_list',
              'venv.lib.python3.6.site-packages.twilio.rest.api.v2010.account.sip.ip_access_control_list',
              'venv.lib.python3.6.site-packages.twilio.rest.api.v2010.account.call',
              'venv.lib.python3.6.site-packages.twilio.rest.api.v2010.account.queue',
              'venv.lib.python3.6.site-packages.twilio.rest.api.v2010.account.usage',
              'venv.lib.python3.6.site-packages.twilio.rest.api.v2010.account.usage.record',
              'venv.lib.python3.6.site-packages.twilio.rest.api.v2010.account.address',
              'venv.lib.python3.6.site-packages.twilio.rest.api.v2010.account.message',
              'venv.lib.python3.6.site-packages.twilio.rest.api.v2010.account.recording',
              'venv.lib.python3.6.site-packages.twilio.rest.api.v2010.account.recording.add_on_result',
              'venv.lib.python3.6.site-packages.twilio.rest.api.v2010.account.recording.add_on_result.payload',
              'venv.lib.python3.6.site-packages.twilio.rest.api.v2010.account.conference',
              'venv.lib.python3.6.site-packages.twilio.rest.api.v2010.account.incoming_phone_number',
              'venv.lib.python3.6.site-packages.twilio.rest.api.v2010.account.incoming_phone_number.assigned_add_on',
              'venv.lib.python3.6.site-packages.twilio.rest.api.v2010.account.available_phone_number',
              'venv.lib.python3.6.site-packages.twilio.rest.fax', 'venv.lib.python3.6.site-packages.twilio.rest.fax.v1',
              'venv.lib.python3.6.site-packages.twilio.rest.fax.v1.fax',
              'venv.lib.python3.6.site-packages.twilio.rest.chat',
              'venv.lib.python3.6.site-packages.twilio.rest.chat.v1',
              'venv.lib.python3.6.site-packages.twilio.rest.chat.v1.service',
              'venv.lib.python3.6.site-packages.twilio.rest.chat.v1.service.user',
              'venv.lib.python3.6.site-packages.twilio.rest.chat.v1.service.channel',
              'venv.lib.python3.6.site-packages.twilio.rest.chat.v2',
              'venv.lib.python3.6.site-packages.twilio.rest.chat.v2.service',
              'venv.lib.python3.6.site-packages.twilio.rest.chat.v2.service.user',
              'venv.lib.python3.6.site-packages.twilio.rest.chat.v2.service.channel',
              'venv.lib.python3.6.site-packages.twilio.rest.sync',
              'venv.lib.python3.6.site-packages.twilio.rest.sync.v1',
              'venv.lib.python3.6.site-packages.twilio.rest.sync.v1.service',
              'venv.lib.python3.6.site-packages.twilio.rest.sync.v1.service.document',
              'venv.lib.python3.6.site-packages.twilio.rest.sync.v1.service.sync_map',
              'venv.lib.python3.6.site-packages.twilio.rest.sync.v1.service.sync_list',
              'venv.lib.python3.6.site-packages.twilio.rest.sync.v1.service.sync_stream',
              'venv.lib.python3.6.site-packages.twilio.rest.proxy',
              'venv.lib.python3.6.site-packages.twilio.rest.proxy.v1',
              'venv.lib.python3.6.site-packages.twilio.rest.proxy.v1.service',
              'venv.lib.python3.6.site-packages.twilio.rest.proxy.v1.service.session',
              'venv.lib.python3.6.site-packages.twilio.rest.proxy.v1.service.session.participant',
              'venv.lib.python3.6.site-packages.twilio.rest.video',
              'venv.lib.python3.6.site-packages.twilio.rest.video.v1',
              'venv.lib.python3.6.site-packages.twilio.rest.video.v1.room',
              'venv.lib.python3.6.site-packages.twilio.rest.video.v1.room.recording',
              'venv.lib.python3.6.site-packages.twilio.rest.video.v1.room.room_participant',
              'venv.lib.python3.6.site-packages.twilio.rest.video.v1.recording',
              'venv.lib.python3.6.site-packages.twilio.rest.video.v1.composition',
              'venv.lib.python3.6.site-packages.twilio.rest.notify',
              'venv.lib.python3.6.site-packages.twilio.rest.notify.v1',
              'venv.lib.python3.6.site-packages.twilio.rest.notify.v1.service',
              'venv.lib.python3.6.site-packages.twilio.rest.notify.v1.service.user',
              'venv.lib.python3.6.site-packages.twilio.rest.studio',
              'venv.lib.python3.6.site-packages.twilio.rest.studio.v1',
              'venv.lib.python3.6.site-packages.twilio.rest.studio.v1.flow',
              'venv.lib.python3.6.site-packages.twilio.rest.studio.v1.flow.engagement',
              'venv.lib.python3.6.site-packages.twilio.rest.studio.v1.flow.engagement.step',
              'venv.lib.python3.6.site-packages.twilio.rest.lookups',
              'venv.lib.python3.6.site-packages.twilio.rest.lookups.v1',
              'venv.lib.python3.6.site-packages.twilio.rest.monitor',
              'venv.lib.python3.6.site-packages.twilio.rest.monitor.v1',
              'venv.lib.python3.6.site-packages.twilio.rest.preview',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.sync',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.sync.service',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.sync.service.document',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.sync.service.sync_map',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.sync.service.sync_list',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.proxy',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.proxy.service',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.proxy.service.session',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.proxy.service.session.participant',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.studio',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.studio.flow',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.studio.flow.engagement',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.wireless',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.wireless.sim',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.understand',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.understand.service',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.understand.service.intent',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.understand.service.field_type',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.marketplace',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.marketplace.available_add_on',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.marketplace.installed_add_on',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.acc_security',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.acc_security.service',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.bulk_exports',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.bulk_exports.export',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.hosted_numbers',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.hosted_numbers.authorization_document',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.deployed_devices',
              'venv.lib.python3.6.site-packages.twilio.rest.preview.deployed_devices.fleet',
              'venv.lib.python3.6.site-packages.twilio.rest.pricing',
              'venv.lib.python3.6.site-packages.twilio.rest.pricing.v1',
              'venv.lib.python3.6.site-packages.twilio.rest.pricing.v1.voice',
              'venv.lib.python3.6.site-packages.twilio.rest.pricing.v1.messaging',
              'venv.lib.python3.6.site-packages.twilio.rest.pricing.v1.phone_number',
              'venv.lib.python3.6.site-packages.twilio.rest.accounts',
              'venv.lib.python3.6.site-packages.twilio.rest.accounts.v1',
              'venv.lib.python3.6.site-packages.twilio.rest.accounts.v1.credential',
              'venv.lib.python3.6.site-packages.twilio.rest.trunking',
              'venv.lib.python3.6.site-packages.twilio.rest.trunking.v1',
              'venv.lib.python3.6.site-packages.twilio.rest.trunking.v1.trunk',
              'venv.lib.python3.6.site-packages.twilio.rest.wireless',
              'venv.lib.python3.6.site-packages.twilio.rest.wireless.v1',
              'venv.lib.python3.6.site-packages.twilio.rest.wireless.v1.sim',
              'venv.lib.python3.6.site-packages.twilio.rest.messaging',
              'venv.lib.python3.6.site-packages.twilio.rest.messaging.v1',
              'venv.lib.python3.6.site-packages.twilio.rest.messaging.v1.service',
              'venv.lib.python3.6.site-packages.twilio.rest.taskrouter',
              'venv.lib.python3.6.site-packages.twilio.rest.taskrouter.v1',
              'venv.lib.python3.6.site-packages.twilio.rest.taskrouter.v1.workspace',
              'venv.lib.python3.6.site-packages.twilio.rest.taskrouter.v1.workspace.task',
              'venv.lib.python3.6.site-packages.twilio.rest.taskrouter.v1.workspace.worker',
              'venv.lib.python3.6.site-packages.twilio.rest.taskrouter.v1.workspace.workflow',
              'venv.lib.python3.6.site-packages.twilio.rest.taskrouter.v1.workspace.task_queue',
              'venv.lib.python3.6.site-packages.twilio.rest.ip_messaging',
              'venv.lib.python3.6.site-packages.twilio.rest.ip_messaging.v1',
              'venv.lib.python3.6.site-packages.twilio.rest.ip_messaging.v1.service',
              'venv.lib.python3.6.site-packages.twilio.rest.ip_messaging.v1.service.user',
              'venv.lib.python3.6.site-packages.twilio.rest.ip_messaging.v1.service.channel',
              'venv.lib.python3.6.site-packages.twilio.rest.ip_messaging.v2',
              'venv.lib.python3.6.site-packages.twilio.rest.ip_messaging.v2.service',
              'venv.lib.python3.6.site-packages.twilio.rest.ip_messaging.v2.service.user',
              'venv.lib.python3.6.site-packages.twilio.rest.ip_messaging.v2.service.channel',
              'venv.lib.python3.6.site-packages.twilio.twiml', 'venv.lib.python3.6.site-packages.certifi',
              'venv.lib.python3.6.site-packages.chardet', 'venv.lib.python3.6.site-packages.chardet.cli',
              'venv.lib.python3.6.site-packages.urllib3', 'venv.lib.python3.6.site-packages.urllib3.util',
              'venv.lib.python3.6.site-packages.urllib3.contrib',
              'venv.lib.python3.6.site-packages.urllib3.contrib._securetransport',
              'venv.lib.python3.6.site-packages.urllib3.packages',
              'venv.lib.python3.6.site-packages.urllib3.packages.backports',
              'venv.lib.python3.6.site-packages.urllib3.packages.ssl_match_hostname',
              'venv.lib.python3.6.site-packages.requests', 'venv.lib.python3.6.site-packages.setuptools',
              'venv.lib.python3.6.site-packages.setuptools.extern',
              'venv.lib.python3.6.site-packages.setuptools._vendor',
              'venv.lib.python3.6.site-packages.setuptools._vendor.packaging',
              'venv.lib.python3.6.site-packages.setuptools.command', 'venv.lib.python3.6.site-packages.pkg_resources',
              'venv.lib.python3.6.site-packages.pkg_resources.extern',
              'venv.lib.python3.6.site-packages.pkg_resources._vendor',
              'venv.lib.python3.6.site-packages.pkg_resources._vendor.packaging'],
    url='https://github.com/HH0718/ScammerFlooder',
    license='MIT',
    author='James Thrasher',
    author_email='James.s.miller1@gmail.com',
    description='Simple script to automate calls and playback messages using Twilio'
)
